# Generated by Django 3.2.6 on 2025-11-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_conversation_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='title',
        ),
        migrations.AddField(
            model_name='conversationanalysis',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
