# Generated by Django 3.2.6 on 2025-11-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationanalysis',
            name='accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='conversationanalysis',
            name='completeness',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='conversationanalysis',
            name='escalation_need',
            field=models.BooleanField(default=False),
        ),
    ]
